name: cron-schedule-updater
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,8,16,24,32,40,48,56 * * * *'

jobs:
  empty_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Empty Commit
      run: git commit --allow-empty -m "Empty commit"

    - name: Push Empty Commit
      run: git push origin main  # Change 'main' to your branch name
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
# jobs:
#   job_1:
#       runs-on: ubuntu-latest
#       steps:
#           - run: git commit --allow-empty -m "Empty-Commit"
#           - run: git push origin main
#       env:
#         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
